ALTER TABLE users
  ADD COLUMN kycStatus ENUM('NOT_STARTED','PENDING','VERIFIED','REJECTED') NOT NULL DEFAULT 'NOT_STARTED',
  ADD COLUMN kycUpdatedAt DATETIME NULL,
  ADD COLUMN kycReviewedBy INT NULL,
  ADD COLUMN kycRejectionReason VARCHAR(255) NULL;
